name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run deployment commands via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOSTNAME: ${{secrets.USERNAME}}
          SSH_IP: ${{secrets.HOST}}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          mkdir -p ~/.ssh

          # Debug output
          echo "Running ssh-keyscan"
          ssh-keyscan -H "$SSH_IP" >> ~/.ssh/known_hosts
          echo "ssh-keyscan completed"

          # Debug output
          echo "Connecting to remote server"
          ssh -i private_key "$SSH_HOSTNAME"@"$SSH_IP" << 'EOF'
            echo "Connected to remote server"
            cd ./testing/CICD_test/ || { echo "cd failed"; exit 1; }
            git pull origin main || { echo "git pull failed"; exit 1; }
            sudo docker-compose -f ./docker.yml up -d --build || { echo "docker-compose failed"; exit 1; }
          EOF

          # Debug output
          echo "Remote commands executed"

        shell: bash
