name: CI/CD Pipeline

on: [push]

jobs:
  deploy:
    runs-on: self_hosted
    
    steps:
    - name: Run deployment commands via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOSTNAME: ${{secrets.USERNAME}}
        SSH_IP: ${{secrets.HOST}}
      run: |
       EOF
          cd ./testing/CICD_test/
          git pull origin main
          sudo docker-compose -f ./docker.yml up -d --build
        EOF
      shell: bash
